services:
  frontend:
    build:
      context: .
      args:
        BASE_URL: /
        API_URL: ${VITE_API_URL:-/solve}
    depends_on:
      - server
    ports:
      - "80:80"

  server:
    build: ./server
